### ISSUE TITLE
Getting error using lib-idn

### ISSUE THREAD

**Issue by tclaus** [deepfryed/idn-ruby#12]
On my Mac Silicon I get the error: 

dlopen(/Users/user/.rvm/gems/ruby-3.0.3/gems/idn-ruby-0.1.4/lib/idn.bundle, 0x0009): symbol not found in flat namespace '_idn_free' - /Users/user/.rvm/gems/ruby-3.0.3/gems/idn-ruby-0.1.4/lib/idn.bundle

I have tries the standard `gem installed-ruby` as well as the recommended: `gem install idn-ruby -- --with-idn-dir=$(brew --prefix libidn)`

I also uninstalled - and reinstalled libidn with brew (brew uninstall libidn / brew install libidn) 

Any Ideas or tips?

**Comment by deepfryed** [comment]
Sorry I don't have M1 Mac to check. I would reinstall ruby 3.0.3 via rvm to use the appropriate architecture, reinstall libidn and then retry.

**Comment by KevinColemanInc** [comment]
I am also having problems on an m1 with this gem in ruby 2.7.4

```
gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
gems/json-1.8.6/lib/json/common.rb:155: warning: Using the last argument as keyword parameters is deprecated
Traceback (most recent call last):
        25: from bin/rails:4:in `<main>'
        24: from bin/rails:4:in `require'
        23: from gems/railties-5.2.4.3/lib/rails/commands.rb:18:in `<top (required)>'
        22: from gems/railties-5.2.4.3/lib/rails/command.rb:46:in `invoke'
        21: from gems/railties-5.2.4.3/lib/rails/command/base.rb:69:in `perform'
        20: from gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        19: from gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        18: from gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        17: from gems/railties-5.2.4.3/lib/rails/commands/console/console_command.rb:95:in `perform'
        16: from gems/railties-5.2.4.3/lib/rails/command/actions.rb:14:in `require_application_and_environment!'
        15: from gems/railties-5.2.4.3/lib/rails/command/actions.rb:22:in `require_application!'
        14: from gems/railties-5.2.4.3/lib/rails/command/actions.rb:22:in `require'
        13: from /Users/kevin/projects/nightsprout/wwc/config/application.rb:10:in `<top (required)>'
        12: from gems/bundler-2.3.9/lib/bundler.rb:176:in `require'
        11: from gems/bundler-2.3.9/lib/bundler/runtime.rb:44:in `require'
        10: from gems/bundler-2.3.9/lib/bundler/runtime.rb:44:in `each'
         9: from gems/bundler-2.3.9/lib/bundler/runtime.rb:55:in `block in require'
         8: from gems/bundler-2.3.9/lib/bundler/runtime.rb:55:in `each'
         7: from gems/bundler-2.3.9/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
         6: from gems/bundler-2.3.9/lib/bundler/runtime.rb:60:in `require'
         5: from gems/twitter-text-3.1.0/lib/twitter-text.rb:27:in `<top (required)>'
         4: from gems/twitter-text-3.1.0/lib/twitter-text.rb:27:in `each'
         3: from gems/twitter-text-3.1.0/lib/twitter-text.rb:28:in `block in <top (required)>'
         2: from gems/twitter-text-3.1.0/lib/twitter-text.rb:28:in `require'
         1: from gems/twitter-text-3.1.0/lib/twitter-text/extractor.rb:6:in `<top (required)>'
gems/twitter-text-3.1.0/lib/twitter-text/extractor.rb:6:in `require': dlopen(gems/idn-ruby-0.1.4/lib/idn.bundle, 0x0009): symbol not found in flat namespace '_idn_free' - gems/idn-ruby-0.1.4/lib/idn.bundle (LoadError)
```

**Comment by tclaus** [comment]
After deleting the folders and reinstalling again with: 
`bundle config build.idn-ruby --with-idn-dir="$(brew --prefix)"`
It no works on the M1 - in my case

**Comment by KevinColemanInc** [comment]
@tclaus I just found that too.

For anyone else, this cmd will delete all of your gems:
```
bundle list | ruby -e 'ARGF.readlines[1..-1].each {|l| g = l.split(" ");  puts "Removing #{g[1]}"; `gem uninstall --force #{g[1]} -v #{g[2].gsub(/\(|\)/, "")}`; }'
```
